version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: fittrack-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fittrack123
      POSTGRES_DB: fittrack
    ports:
      - '5432:5432'
    volumes:
      - fittrack_pgdata:/var/lib/postgresql/data

volumes:
  fittrack_pgdata: